### ISSUE TITLE
TLS_FLAVOR=notls fails

### ISSUE THREAD

**Issue by jjj0** [heviat/Mailu#8]
## Version

- Version: `master`

## Description

The front container does not work with TLS_FLAVOR=notls set.

## Replication Steps

Start Mailu-OpenID with TLS_FLAVOR=notls

## Observed behaviour

Front container not working.

## Expected behaviour

Front container working without TLS

## Logs

Traceback (most recent call last):
  File "/config.py", line 48, in <module>
    if "TLS" in args and not all(os.path.exists(file_path) for file_path in args["TLS"]):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Wombosvideo** [comment]
Thank you for bringing this to our attention. The latest version of Mailu changes some things in terms of versioning and configuration. Since the Mailu Setup (`docker-compose.yml` and `mailu.env` generator) doesn't allow selecting the old version, things are broken at the moment. We are currently in the procress of migrating `Mailu-OpenID` to version `2024.06` so you can use the Setup with all the available options again. This means that you won't be able to use `notls` until then. In the meantime, you can use the [`mailu` v2.0 documentation](https://mailu.io/2.0/) to find out how to backport the generated config files.

**Comment by Wombosvideo** [comment]
We have now updated Mailu and moved our OIDC implementation to the new [`Mailu-OIDC`](https://github.com/heviat/Mailu-OIDC) fork. Please check whether this issue still persists in the latest release. If it does, please open an issue for the new fork and try to make sure upstream [Mailu](https://github.com/mailu/mailu) is unaffected by this issue.

The Docker image releases are currently still in this fork, but we're going to change that soon. When we do, `Mailu-OpenID` will no longer be supported.
